const data = {
  products: [
    {
      name: 'cello ball point pen',
      slug: 'cello-ball-pen',
      category: 'pen',
      image: '/image/p11.jpeg', //679x829
      price: 120,
      brand: 'cello',
      rating: 4.2,
      numReviews: 10,
      description: 'high quality',
    },
    {
      name: 'cello ball point pen',
      slug: 'cello-ball-pen',
      category: 'pen',
      image: '/image/p12.jpeg',
      price: 120,
      brand: 'cello',
      rating: 4.2,
      numReviews: 10,
      description: 'high quality',
    },
    {
      name: 'cello ball point pen',
      slug: 'cello-ball-pen',
      category: 'pen',
      image: '/image/p11.jpeg',
      price: 120,
      brand: 'cello',
      rating: 4.2,
      numReviews: 10,
      description: 'high quality',
    },
    {
      name: 'cello ball point pen',
      slug: 'cello-ball-pen',
      category: 'pen',
      image: '/image/p12.jpeg',
      price: 120,
      brand: 'cello',
      rating: 4.2,
      numReviews: 10,
      description: 'high quality',
    },
    {
      name: 'cello ball point pen',
      slug: 'cello-ball-pen',
      category: 'pen',
      image: '/image/p12.jpeg',
      price: 120,
      brand: 'cello',
      rating: 4.2,
      numReviews: 10,
      description: 'high quality',
    },
  ],
};
export default data;
