const data = {
  products: [
    {
      name: 'cello ball point pen',
      slug: 'cello-ball-pen1',
      category: 'pen',
      image: '/image/p11.jpeg', //679x829
      price: 120,
      brand: 'cello',
      rating: 4.2,
      numReviews: 10,
      countInStock: 12,
      description: 'high quality',
    },
    {
      name: 'cello ball point pen',
      slug: 'cello-ball-pen2',
      category: 'pen',
      image: '/image/p12.jpeg',
      price: 120,
      brand: 'cello',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'high quality',
    },
    {
      name: 'cello ball point pen',
      slug: 'cello-ball-pen3',
      category: 'pen',
      image: '/image/p11.jpeg',
      price: 120,
      brand: 'cello',
      rating: 4.2,
      numReviews: 10,
      countInStock: 5,
      description: 'high quality',
    },
    {
      name: 'cello ball point pen',
      slug: 'cello-ball-pen4',
      category: 'pen',
      image: '/image/p12.jpeg',
      price: 120,
      brand: 'cello',
      rating: 4.2,
      numReviews: 10,
      countInStock: 5,
      description: 'high quality',
    },
    {
      name: 'cello ball point pen',
      slug: 'cello-ball-pen5',
      category: 'pen',
      image: '/image/p12.jpeg',
      price: 120,
      brand: 'cello',
      rating: 4.2,
      numReviews: 10,
      countInStock: 5,
      description: 'high quality',
    },
  ],
};
export default data;
