const data = {
  products: [
    {
      //_id: '1',
      name: 'cello ball point pen-1',
      slug: 'cello-ball-pen1',
      category: 'pen',
      image: '/image/p11.jpeg', //679x829
      price: 120,
      brand: 'cello',
      rating: 4.2,
      numReviews: 10,
      countInStock: 12,
      description: 'high quality',
    },
    {
      //_id: '2',
      name: 'cello ball point pen-2',
      slug: 'cello-ball-pen2',
      category: 'pen',
      image: '/image/p12.jpeg',
      price: 120,
      brand: 'cello',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'high quality',
    },
    {
      //_id: '3',
      name: 'cello ball point pen-3',
      slug: 'cello-ball-pen3',
      category: 'pen',
      image: '/image/p11.jpeg',
      price: 120,
      brand: 'cello',
      rating: 4.2,
      numReviews: 10,
      countInStock: 5,
      description: 'high quality',
    },
    {
      //_id: '4',
      name: 'cello ball point pen-4',
      slug: 'cello-ball-pen4',
      category: 'pen',
      image: '/image/p12.jpeg',
      price: 120,
      brand: 'cello',
      rating: 4.2,
      numReviews: 10,
      countInStock: 5,
      description: 'high quality',
    },
    {
      //_id: '5',
      name: 'cello ball point pen*5',
      slug: 'cello-ball-pen5',
      category: 'pen',
      image: '/image/p12.jpeg',
      price: 120,
      brand: 'cello',
      rating: 4.2,
      numReviews: 10,
      countInStock: 0,
      description: 'high quality',
    },
  ],
};
export default data;
